import type { Plan } from "@/types/pricing"

export const plans: Plan[] = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for getting started",
    price: 0,
    currency: "USD",
    interval: "month",
    features: [
      { text: "100 API calls per month", included: true },
      { text: "Basic language support", included: true },
      { text: "1 project", included: true },
      { text: "Email support", included: true },
      { text: "Advanced analytics", included: false },
      { text: "Custom models", included: false },
      { text: "Priority support", included: false },
    ],
    highlighted: false,
    cta: "Get Started",
  },
  {
    id: "pro",
    name: "Pro",
    description: "For professionals and small teams",
    price: 29,
    currency: "USD",
    interval: "month",
    features: [
      { text: "10,000 API calls per month", included: true },
      { text: "Full language support", included: true },
      { text: "Unlimited projects", included: true },
      { text: "Email support", included: true },
      { text: "Advanced analytics", included: true },
      { text: "Custom models", included: false },
      { text: "Priority support", included: false },
    ],
    highlighted: true,
    popular: true,
    cta: "Upgrade to Pro",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "For large-scale deployments",
    price: 199,
    currency: "USD",
    interval: "month",
    features: [
      { text: "Unlimited API calls", included: true },
      { text: "Full language support", included: true },
      { text: "Unlimited projects", included: true },
      { text: "Priority support", included: true },
      { text: "Advanced analytics", included: true },
      { text: "Custom models", included: true },
      { text: "Dedicated account manager", included: true },
    ],
    highlighted: true,
    cta: "Contact Sales",
  },
]
